import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

describe("tourist phone preview", () => {
  const phone = readFileSync(path.join(process.cwd(), "src/components/PhoneApp.tsx"), "utf8");
  const css = readFileSync(path.join(process.cwd(), "src/app/globals.css"), "utf8");

  it("defaults to Weekend with Joanna's locked IA and logo fallback", () => {
    expect(phone).toContain('useState<TimeTab>("weekend")');
    expect(phone).toContain("location.hash");
    expect(phone).toContain("Today");
    expect(phone).toContain("Weekend");
    expect(phone).toContain("Week");
    expect(phone).toContain("Cal");
    expect(phone).toContain("Community");
    expect(phone).toContain("Featured");
    expect(phone).toContain("featured-grid");
    expect(phone).toContain("photo-stack");
    expect(phone).toContain("visually-hidden");
    expect(phone).toContain("This Weekend");
    expect(phone).toContain("Today •");
    expect(phone).not.toContain('label: "Family"');
    expect(phone).toContain("{event.venue}");
    expect(phone).toContain("st-d-paragraph");
    expect(phone).toContain("Event Details");
    expect(phone.indexOf("photo-card__when")).toBeLessThan(phone.indexOf("photo-card__title"));
    expect(phone).toContain("photo-card__media");
    expect(phone).toContain("photo-card__body");
    expect(phone).not.toContain("photo-card__overlay");
    expect(css).toContain("photo-card__body");
    expect(css).not.toContain("photo-card__overlay");
    expect(css).not.toContain("text-overflow: ellipsis");
    expect(css).toContain("flex-wrap: wrap");
    expect(css).toContain("min-width: max-content");
    expect(css).toContain("flex: 0 0 auto");
    expect(css).toContain("featured-grid");
    expect(css).toContain("grid-template-columns: 1fr 1fr");
    expect(css).toContain("phone-cats__on");
    expect(css).toContain("min(390px, 100%)");
    expect(phone).toContain("MonthCalendar");
    expect(phone).toContain('event.image ?? "/brand/visit-aky-logo.png"');
    expect(phone).not.toMatch(/chip|pill|badge/i);
  });
});

describe("Dana weekend preview", () => {
  const dana = readFileSync(path.join(process.cwd(), "public/dana.html"), "utf8");

  it("shows Sean's verified weekend rows with the Visit AKY logo fallback", () => {
    expect(dana).toContain("ashland-tomcats-volleyball-johnson-central-2026-08-29");
    expect(dana).toContain("fairview-eagles-volleyball-rose-hill-2026-08-29");
    expect(dana).toContain("ashland-tomcats-volleyball-wolfe-county-2026-08-29");
    expect(dana).toContain("sandys-exacta-giveaway-bronco-sport-2026-08-29");
    expect(dana).toContain("boyd-library-midland-novel-tea-book-club-2026-08-31");
    expect(dana).toContain("boyd-lions-girls-soccer-greenup-2026-08-31");
    expect(dana).toContain("boyd-lions-boys-soccer-greenup-2026-08-31");
    expect(dana).toContain("./brand/visit-aky-logo.png");
    expect(dana).toContain("Cal");
    expect(dana).toContain("Weekend");
    expect(dana).toContain("Community");
    expect(dana).not.toContain(">Family</button>");
    expect(dana).toContain("Event Details");
    expect(dana).toContain("photo-card__venue");
    expect(dana).toContain("Blazer High School");
    expect(dana).toContain("Fairview High School");
    expect(dana).toContain("Sandy's Racing & Gaming");
    expect(dana).toContain('event.category === "family"');
    expect(dana).toContain("filterSports");
    expect(dana).toContain('data-time="weekend"');
    expect(dana).toContain('data-time="today"');
    expect(dana).toContain('data-cat="sports"');
    expect(dana).toContain('data-cat="community"');
    expect(dana).toContain("photo-card__image--logo");
    expect(dana).toContain("photo-card__media");
    expect(dana).toContain("photo-card__body");
    expect(dana).not.toContain("photo-card__overlay");
    expect(dana).not.toContain("text-overflow: ellipsis");
    expect(dana).not.toMatch(/photo-card[^}]*white-space:\s*nowrap/);
    expect(dana).toContain("flex-wrap: wrap");
    expect(dana).toContain("min-width: max-content");
    expect(dana).toContain("flex: 0 0 auto");
    expect(dana).toContain(">Community</button>");
    expect(dana).toContain("THIS_WEEK_HEADLINERS");
    expect(dana).toContain("deana-carter");
    expect(dana).toContain("makers-market");
    expect(dana).toContain("featured-grid");
    expect(dana).toContain("Featured");
    expect(dana).toContain("linear-gradient(160deg, #326dcd, #7b5bbb)");
    expect(dana).not.toMatch(/background:\s*#000/);
    expect(dana).toContain("min-height: 110px");
    expect(dana).not.toContain("min-height: 320px");
    expect(dana).toContain("grid-template-columns: 1fr 1fr");
    expect(dana).toContain("This Week • SAT 29–FRI 4");
    expect(dana).toContain("Today • SAT AUG 29");
    expect(dana).toContain("ashland-tomcats-volleyball-wolfe-county-2026-08-29");
    expect(dana).toMatch(/first\[\\s-\]\?friday/i);
    expect(dana).toContain("facebook-first-friday-2026-09-04");
    expect(dana).toContain("First Friday September");
    expect(dana).not.toMatch(/localhost/);
    expect(dana).not.toContain("disabled>");
    expect(dana).toContain("(left.startsMs - right.startsMs)");
    expect(dana).not.toContain("(RANK[left.category] - RANK[right.category]) || (left.startsMs - right.startsMs)");
  });
});
